# Generated by Django 4.0.3 on 2022-04-16 20:38

import api.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='challenges',
            fields=[
                ('challenge_id', models.IntegerField(primary_key=True, serialize=False)),
                ('challenges', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='lobbies',
            fields=[
                ('room_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('room_code', models.CharField(default=api.models.roomGuid, max_length=5, unique=True)),
                ('room_host', models.CharField(max_length=20)),
                ('numPlayers', models.IntegerField(default=1)),
                ('numBetted', models.IntegerField(default=0)),
                ('players_playing', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='players',
            fields=[
                ('player_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=20)),
                ('is_playing', models.BooleanField(null=True)),
                ('bet_for', models.CharField(max_length=20, null=True)),
                ('room_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lobbies')),
            ],
        ),
    ]
