# Generated by Django 4.0.3 on 2022-03-31 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomCode', models.CharField(default='', max_length=10, unique=True)),
                ('roomHost', models.CharField(default='none', max_length=70, unique=True)),
                ('numPlayers', models.IntegerField(default=1)),
            ],
        ),
    ]
