# Generated by Django 4.0.3 on 2022-04-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomHost',
            field=models.CharField(default='none', max_length=5),
        ),
    ]
