# Generated by Django 4.0.3 on 2022-04-03 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_room_testfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='challenges',
            fields=[
                ('challenge_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('challenge_str', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='lobbies',
            fields=[
                ('room_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('room_code', models.CharField(max_length=5)),
                ('room_host', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='players',
            fields=[
                ('player_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=20)),
                ('room_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lobbies')),
            ],
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
