# Generated by Django 4.0.3 on 2022-04-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_players_is_playing'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='bet_for',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
