# Generated by Django 4.0.3 on 2022-04-10 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_room_roomhost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomHost',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
