# Generated by Django 4.0.3 on 2022-04-12 02:43

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_room_roomhost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.AddField(
            model_name='lobbies',
            name='numPlayers',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='lobbies',
            name='room_code',
            field=models.CharField(default=api.models.roomGuid, max_length=5, unique=True),
        ),
    ]
